# Generated by Django 5.0.6 on 2026-05-17 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre del/la artista')),
                ('brand_name', models.CharField(max_length=120, verbose_name='Nombre de la marca')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('image_url', models.URLField(blank=True, help_text='Pega una URL pública. Si usas Cloudinary, usa el campo image.', max_length=500, verbose_name='URL de la foto del artista')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artists/', verbose_name='Imagen (Cloudinary)')),
                ('iconic_song_title', models.CharField(max_length=120, verbose_name='Canción icónica')),
                ('iconic_song_url', models.URLField(help_text='URL directa a un mp3/preview (Spotify preview, Cloudinary, etc.)', max_length=500, verbose_name='URL del audio de la canción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nombre del producto')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio (USD)')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL de la imagen')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen (Cloudinary)')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, help_text='De 0 a 5', max_digits=3, verbose_name='Rating')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='¿Es best seller?')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='Stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.artist', verbose_name='Artista/Marca')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-is_bestseller', '-rating', 'name'],
            },
        ),
    ]
